#!/bin/sh

start() {
  /etc/options_menu/optiond &
}

stop() {
	killall optiond
	killall options
	rm -f /tmp/options.flag
}

case "$1" in
start)
	start
;;
stop)
	stop
;;
restart)
	stop
	start
;;
*)
	echo "optiond: Please use start, stop, or restart."
	exit 1
;;
esac
